using System.Collections.Generic;

/*
 * The code below was generated by a tool
 *
 *
 */
namespace DTOGen.Examples
{
// ReSharper disable InconsistentNaming
	public partial class Affectation 
	{
		public Affectation()
	    {
			FonctionsSecondaires = new List<Affectation_FonctionsSecondaires_Item>();
			AddressesEmails = new List<string>();
	    }

		public int Id { get; set; }
		public bool IsPrincipale { get; set; }
		public int Statut { get; set; }
		public MiniBureau Bureau { get; set; }
		public List<Affectation_FonctionsSecondaires_Item> FonctionsSecondaires { get; private set; }
		public MiniFonction Fonction { get; set; }
		public MiniAgent Agent { get; set; }
		public List<string> AddressesEmails { get; private set; }
	} // end class

	public partial class Affectation_FonctionsSecondaires_Item 
	{
		public Affectation_FonctionsSecondaires_Item()
	    {
	    }

		public int Id { get; set; }
		public string Libelle { get; set; }
	} // end class

	public partial class Agent 
	{
		public Agent()
	    {
	    }

		public int Id { get; set; }
		public string Nom { get; set; }
		public string Prenom { get; set; }
		public string NomDeFamille { get; set; }
		public string Civilité { get; set; }
	} // end class

	public partial class MiniAgent 
	{
		public MiniAgent()
	    {
	    }

		public int Id { get; set; }
		public string Prenom { get; set; }
		public string Nom { get; set; }
	} // end class

	public partial class Fonction 
	{
		public Fonction()
	    {
	    }

		public int Id { get; set; }
		public string Libelle { get; set; }
		public string LibelleFeminin { get; set; }
	} // end class

	public partial class MiniFonction 
	{
		public MiniFonction()
	    {
	    }

		public int Id { get; set; }
		public string Libelle { get; set; }
	} // end class

	public partial class Bureau 
	{
		public Bureau()
	    {
	    }

		public int Id { get; set; }
		public string Libelle { get; set; }
		public string LibelleCourt { get; set; }
		public Bureau_TypeBureau TypeBureau { get; set; }
		public Bureau_Entité Entité { get; set; }
	} // end class

	public partial class Bureau_TypeBureau 
	{
		public Bureau_TypeBureau()
	    {
	    }

		public int Id { get; set; }
		public string Libelle { get; set; }
	} // end class

	public partial class Bureau_Entité 
	{
		public Bureau_Entité()
	    {
	    }

		public int Id { get; set; }
		public string Libelle { get; set; }
	} // end class

	public partial class MiniBureau 
	{
		public MiniBureau()
	    {
	    }

		public int Id { get; set; }
		public string Libelle { get; set; }
		public string LibelleCourt { get; set; }
		public MiniBureau_TypeBureau TypeBureau { get; set; }
	} // end class

	public partial class MiniBureau_TypeBureau 
	{
		public MiniBureau_TypeBureau()
	    {
	    }

		public int Id { get; set; }
		public string Libelle { get; set; }
	} // end class

// ReSharper restore InconsistentNaming
} // end namespace